name: 'booking_pipeline'
version: '1.0.0'
config-version: 2
profile: 'booking_pipeline'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  booking_pipeline:
    staging:
      +schema: silver
      +materialized: table
    marts:
      +schema: gold
      +materialized: table

vars:
  min_bronze_rows: 80000